"""llm-protocols:LLM 提供商协议层(四协议驱动、配置快照、加解密、纯函数工具)。"""

from .client import LLMClient, LLMError
from .config import ResolvedModelConfig, snapshot_model_config
from .crypto import decrypt_secret, derive_fernet_key, encrypt_secret, mask_secret
from .drivers import (
    AnthropicMessagesDriver,
    CancellationToken,
    ChatCompletionsDriver,
    GeminiGenerateContentDriver,
    OpenAIResponsesDriver,
    ProtocolCallError,
    ProtocolDriver,
)
from .factory import DEFAULT_MODEL_API_TIMEOUT_SECONDS, build_protocol_driver
from .protocols import (
    LEGACY_OPENAI_PROVIDER,
    ModelApiProtocol,
    ModelProtocolError,
    available_model_protocols,
    current_protocol_options,
    model_config_fingerprint,
    normalize_chat_protocol_options,
    resolve_api_protocol,
    validate_model_base_url,
)
from .schemas import (
    ModelCapabilityTestResult,
    ModelConfigCreateRequest,
    ModelConfigRead,
    ModelConfigTestResponse,
    ModelConfigUpdateRequest,
    ModelProviderErrorDetail,
)
from .utils import (
    DEFAULT_INPUT_TOKEN_BUDGET,
    TURN_STAGE_MESSAGE_MARKER,
    content_text,
    extract_json,
    fit_request_messages,
    loads_llm_json,
    normalize_extra_body,
    normalize_thinking_mode,
    request_tokens,
    thinking_mode_for_model,
    thinking_mode_from_extra_body,
    thinking_request_kwargs,
    usage_metrics,
)

__all__ = [
    "AnthropicMessagesDriver",
    "CancellationToken",
    "ChatCompletionsDriver",
    "DEFAULT_INPUT_TOKEN_BUDGET",
    "DEFAULT_MODEL_API_TIMEOUT_SECONDS",
    "GeminiGenerateContentDriver",
    "LEGACY_OPENAI_PROVIDER",
    "LLMClient",
    "LLMError",
    "ModelApiProtocol",
    "ModelCapabilityTestResult",
    "ModelConfigCreateRequest",
    "ModelConfigRead",
    "ModelConfigTestResponse",
    "ModelConfigUpdateRequest",
    "ModelProtocolError",
    "ModelProviderErrorDetail",
    "OpenAIResponsesDriver",
    "ProtocolCallError",
    "ProtocolDriver",
    "ResolvedModelConfig",
    "TURN_STAGE_MESSAGE_MARKER",
    "available_model_protocols",
    "build_protocol_driver",
    "content_text",
    "current_protocol_options",
    "decrypt_secret",
    "derive_fernet_key",
    "encrypt_secret",
    "extract_json",
    "fit_request_messages",
    "loads_llm_json",
    "mask_secret",
    "model_config_fingerprint",
    "normalize_chat_protocol_options",
    "normalize_extra_body",
    "normalize_thinking_mode",
    "request_tokens",
    "resolve_api_protocol",
    "snapshot_model_config",
    "thinking_mode_for_model",
    "thinking_mode_from_extra_body",
    "thinking_request_kwargs",
    "usage_metrics",
    "validate_model_base_url",
]
